= Deploying
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: deploying.adoc
:keywords: deploy, deploying, cloudhub, on premises, on premise

Mule standalone can run multiple applications. This means you can include the same name spaces within different applications and they neither collide nor share information.

In effect, Mule is an app server. Mule checks for new apps (in the apps directory) and starts them.

Mule also restarts apps if it detects that the apps have changed, meaning you can drop a revised version of an existing, running application into the /apps directory, Mule stops the existing app and restarts using the new files.

If Mule is embedded in another container, the xref:3.7@mule-management-console::index.adoc[Mule Management Console] cannot perform auto-discovery or server restarts.

*Deploying Topics:*

* xref:deploy/starting-and-stopping-mule-esb.adoc[Starting and Stopping Mule ESB]
* xref:deploy/deployment-scenarios.adoc[Deployment Scenarios]
* xref:deploy/deploying-to-multiple-environments.adoc[Deploying to Multiple Environments]
* xref:administer/clustering/mule-high-availability-ha-clusters.adoc[Mule High Availability HA Clusters]
* xref:deploy/mule-deployment-model.adoc[Mule Deployment Model]
* xref:mule-server-notifications.adoc[Mule Server Notifications]
* xref:testing/profiling-mule.adoc[Profiling Mule]
* xref:deploy/hardening-your-mule-installation.adoc[Hardening your Mule Installation]
* xref:deploy/configuring-mule-for-standalone-deployment-scenarios.adoc[Configuring Mule for Different Deployment Scenarios]
* xref:5@studio::preparing-a-gitignore-file.adoc[Preparing a gitignore File]