= MUnit
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint studio, testing, test, munit, automation, testing automation

NOTE: For the current version of MUnit, see xref:1.2@munit::index.adoc[MUnit 1.2.0].

Mule testing framework that allows you to:

* mock the output of your message processors
* write tests in XML or Java
* create tests in the Anypoint Studio drag-and-drop interface
* insert spy functionality to track what happens before and after a message processor is called
* view coverage reports in Studio
* run tests with your plugins
* access detailed Mule stacktraces that pinpoint message processor failures
* integrate with Maven and Surefire for continuous integration support

Access MUnit's code repository on https://github.com/mulesoft/munit[github], or install the Studio plugin from the xref:5@studio::install-update-items-in-studio.adoc[Addons update site] within Studio.

Although MUnit is not yet supported by MuleSoft, you can access developer documentation and community FAQs on the https://github.com/mulesoft/munit/wiki[MUnit github wiki page].

== See Also

Check out some examples and discussions of MUnit in these blog posts:

* http://poznachowski.blogspot.in/2014/04/munit-testing-mule-practices-and-some.html[MUnit testing, Mule best practices and more...]
* https://blogs.mulesoft.com/dev/mule-dev/mitm-automated-unit-testing/[Man in the Mirror, Apple's Security Flaw, and the Importance of Unit Testing]