= About the Choice Router
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Choice flow control component dynamically routes execution based on the contents of its input. It adds conditional processing to a flow, similar to an if/then/else code block in most programming languages.

A Choice flow control component uses expressions written in DataWeave language to evaluate the content of the input, it then routes to the first option that matches the expression (evaluates to true).

* A When block is executed when the input matches its condition.

* An optional Else block is executed only if none of the conditions on the When blocks are matched.


You can provide a custom name to each condition, this only has an effect what you see in the editor, not the behavior of the application.



== See Also


* xref:reference/choice-router-xml.adoc[Choice Router XML Reference]

* xref:about/flows.adoc[About Flows]

* xref:dataweave/cookbook/extract-data.adoc[DataWeave Cookbook Extract Data]

* xref:dataweave/dataweave-language-introduction.adoc[DataWeave Language Introduction]