= About the For Each Scope
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The For Each scope (foreach) splits a collection into elements and processes them one by one through the components that you place in the scope. It then regroups them into a single message containing a collection. It's similar to a for-each/for-loop code block in most programming languages.

It can process any type of collection, including maps, lists, arrays.


== Differences With a Splitter

The For Each scope performs a similar task to using a Splitter and then an Aggregator. The main difference is that the For Each scope outputs a collection just like the one it receives, the Aggregator outputs a message where the payload is a list of mule messages (each with its own payload and attributes).


== Custom Parsing

If the input is a simple collection, the For Each scope can parse it without you needing to configure anything.


You can optionally use an expression to split data in a custom way. The following expression makes the For Each scope iterate over an array stored in payload.topics:

"#[payload.topics]"

////
Note that if the input contains information outside the collection you tell it to split, this information is lost.
////

You can also parse an array in batches. Potentially, these batches promote quicker processing. Each batch is treated as a separate Mule message. For example, if a collection has 200 elements and you set the batch size to 50, the For Each scope iteratively processes 4 batches of 50 elements, each as a separate Mule message.

== Error Handling

If one of the elements in a collection throws an exception, the For Each scope stops processing that collection and invokes the error handler.

== Persisting Data

In case the message inside the For Each scope is persisted, not only the item in the collection is serialized but also all the variables associated with it. The rootMessage variable, associated with the message, contains a reference to the complete, unsplit collection. Therefore, serialization/deserialization of the rootMessage variable could impact memory consumption considerably when this collection is large enough.

To avoid this issue you must first remove the rootMessage variable from the message before persisting it.


== See Also

* xref:reference/for-each-scope-xml.adoc[For Each Scope XML Reference]
* xref:concepts/scopes.adoc[About Scopes]

* xref:about/mule-event.adoc[About the Mule Event]
* xref:about/mule-message.adoc[About the Mule Message]